services:
  mongo:
    image: mongo:7.0.12
    volumes:
      - mongo_data:/data/db
    networks:
      - my-cs-admin

  api:
    build:
      context: ./server
      dockerfile: Dockerfile 
    restart: unless-stopped
    env_file: ./server/.env
    volumes:
      - ./server:/app
    networks:
      - my-cs-admin
    ports:
      - 4000:4000

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./client:/app
    networks:
      - my-cs-admin
    command: npm start
    ports:
      - 3000:3000

volumes:
  mongo_data:

networks:
  my-cs-admin:
    driver: bridge

